spring:
  application:
    name:  a-bootiful-client
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    healthcheck:
      enabled:  true
management:
  security:
    enabled:  false