server:
  port: 8884
  
spring:
  application:
    name:  gateway-service-zuul
      
#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
zuul:
  routes:
    baidu:
      path:  /it/**
      url:  http://www.ityouknow.com/