server:
  port: 8884
  
spring:
  application:
    name:  gateway-service-zuul
#####################################################################    
#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
#下面是固定的配置，即只要有新的url则需要进行一个配置
# zuul:
#   routes:
#     baidu:
#       path:  /it/**
#       url:  http://www.ityouknow.com/
#####################################################################

#实现实例名的映射，可以实现负载均衡
# zuul:
#   routes:
#     api-a:
#       path:  /producer/**
#       serviceId:  a-bootiful-client
# 
# eureka:
#   client:
#     serviceUrl:
#       defaultZone:  http://172.16.188.173:8761/eureka/
##################################################################### 

#下面的配置是不通过服务注册中心进行配置的
ribbon:
  eureka:
    enabled:  false

#配置在配置文件中的路由信息
zuul:
  routes:
    elicense:
      url:  http://localhost:8080/elicense
      path:  /elicense/**







